### ISSUE TITLE
Creating own Loader / Plans for PLYLoader? 

### ISSUE THREAD

**Issue by edimmeduseljac** [demike/ngx-three#10]
I really love the library and your implementation of the loaders, but I'd love to have a loader for .ply files. Are there any plans for a PLYLoader just like the GLTFLoader? 

I've seen the documentation on creating my own loaders, but since I'm fairly new to Angular and don't really have a lot of experience with pipes or directives, I think I'd rather ask for guidance/help. Since three.js includes a [PLYLoader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/PLYLoader.js), this shouldn't be too hard, right?

I would appreciate any kind of help and I'd like thank you very much for the previous support!

**Comment by demike** [comment]
yes I can do that for you. But will take me a week or so, because currently I am finishing an other project.

**Comment by edimmeduseljac** [comment]
Would be perfect, thank you!!

**Comment by edimmeduseljac** [comment]
Hi! Just wanted to come back and ask if there have been any updates on this issue or if you have any idea when you‘re finished with the loader :)

**Comment by demike** [comment]
I will implement it tomorrow

**Comment by demike** [comment]
@edimmeduseljac the ply loader can be used in 0.14.0.
You can take a look at the example: https://demike.github.io/ngx-three/plyloader-example
and/or the documentation: https://github.com/demike/ngx-three#plyloader

**Comment by demike** [comment]
The ply loader should work as can be seen in the example. For further improvements open a new issue!
