### ISSUE TITLE
GLTF Loader Pipe Question

### ISSUE THREAD

**Issue by AnyFinCanHappen** [demike/ngx-three#14]
I noticed in the documentation, when loading a GLTF object using the GLTF Loader Pipe:

`<th-object3D [objRef]="'assets/helmet.glb' | loadGLTF"> </th-object3D>`

But the `thAsyncLoaderBasePipe` returns a Promise and it needs a `Group` object. 
So the code in the documentation should be:

`<th-object3D [objRef]="('assets/helmet.glb' | loadGLTF | async).scene"> </th-object3D>`

I was wondering if this was intentional, if not should the `loadGLTF` pipe handle the Promise?

**Comment by demike** [comment]
@AnyFinCanHappen you are right the documentstion is wrong here.

I thought the pipe should be like the service ( no magic inside)

The directive though is different because the scene has to be applied to the 'underlying' object3d

I will fix the docs when I am back from holiday.

Thanks!

**Comment by AnyFinCanHappen** [comment]
Hope you are enjoying your vacation @demike,

If you want, I can make a quick PR to the documentation with the code snippet above:
`<th-object3D [objRef]="('assets/helmet.glb' | loadGLTF | async).scene"> </th-object3D>`?

Other than that, thank you for the explanation.

Thanks.

**Comment by demike** [comment]
Thanks!
Of course PRs are welcome.
So if you like ...
