### ISSUE TITLE
how to setup Raycaster and outlinePass in ngx-three

### ISSUE THREAD

**Issue by ousc** [demike/ngx-three#26]
This project is a great work, and it's an honor to use this library, but I have a few questions:

1: How to use Raycaster in this library, I want to get the specific coordinates of the click, which makes me have to use Raycaster, but I can't find a way to use Raycaster in ngx-three

2: How to use outlinePass, I tried to put `th-outlinePass` in `th-object3D`, but it didn’t work

**Comment by demike** [comment]
Hi, thanks for the kind words. I am currently on vacation.
Will prepare an example when I am back next week.

**Comment by ousc** [comment]
Thank you for your reply and enjoy your vacation.

**Comment by demike** [comment]
@ousc I have added a new example showing how to use the simplified pointer events handling ( using the raycaster )
in combination with th-outlinePass: https://demike.github.io/ngx-three/outline-pass-events-example
In addition to the target component the `onClick` events (and also most of the others) now also hold the `Intersection` members delivered by the raycaster. 

You can use the additional intersection data as of version 0.26.0
Hope this helps.

**Comment by ousc** [comment]
Thank you for your example. Now I know how to do it.
Does this library have any plans for documentation and promotion now? It is a great library in Angular. It has more angular spirit than angular-three.
