### ISSUE TITLE
CSS2DRenderer In Ngx-Three

### ISSUE THREAD

**Issue by AnyFinCanHappen** [demike/ngx-three#33]
Hey,

I was just wondering if it was possible to use the `CSS2DRenderer` [https://threejs.org/docs/#examples/en/renderers/CSS2DRenderer](url) with NGX Three?

Thanks

**Comment by demike** [comment]
Angular wrappers for the Css2dObject are not yet generated. But it is planned for the near future.
As it will also be the "base building block" of the revamped html view.

For now you can add css2d objects the (non declarative) three.js way and call render on your CSS2DRenderer in the render callback.

**Comment by AnyFinCanHappen** [comment]
Thanks for the reply.

To get this to work, make sure to pass a `Camera` and the a CSS2DRenderer dom element into `args` input in the `th-orbitControls`

```
 <th-perspectiveCamera
    #thCamera
    [args]="[20, 2, 0.5, 1000]"
 >
   <th-orbitControls
       [args]="[thCamera.objRef, labelRenderer.domElement]"
   ></th-orbitControls>
 </th-perspectiveCamera>
```

Then as @demike mentioned, call render in your CSS2DRenderer
```
  <th-canvas
    (onRender)="test($event)"
  >
   ...
  </th-canvas>
```
```
  test(event: {scene: ThScene, camera: ThCamera, renderer: THREE.WebGLRenderer}): void {
    this.labelRenderer.render(event.scene.objRef!, event.camera.objRef!);
  }
```
