### ISSUE TITLE
onRender event not firing

### ISSUE THREAD

**Issue by niccolofanton** [demike/ngx-three#7]
First of all, thank you for the great work you are doing here!
I'm having some issues with the onRender event on ThCanvas, maybe I'm missing something.

template:
```
<th-canvas (onRender)="this.onBeforeRender()">
    <th-scene [background]="'black' | color">

        <th-object3D loadGLTF [position]="[0, 0, 0]" [url]="studioPath" [scale]="[0.1, 0.1, 0.1]">
        </th-object3D>

        <th-object3D loadObj [position]="[7.2, 1, -1.5]" [scale]="[1.4,1.4,1.4]" [rotation]="rotation" [url]="glbPath">
        </th-object3D>

        <th-pointLight [position]="[10, 10, 10]"></th-pointLight>

        <th-perspectiveCamera [args]="[45, 2, 0.1, 100]" [position]="[0, 8, 15]" [lookAt]="[0, 0, 0]">
            <th-orbitControls></th-orbitControls>
        </th-perspectiveCamera>

    </th-scene>
</th-canvas>
```

component:
```
import { Component } from '@angular/core';
// public readonly glbPath = `assets/mask/source/model.glb`;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent {

  public readonly studioPath = `assets/studioB.gltf`;
  public readonly glbPath = `assets/m3nh1r/model/model.obj`;

  public rotation: [x: number, y: number, z: number] = [0, 0, 0];

  ngOnInit(): void { }

  public onBeforeRender() {
    console.log('on render')
    this.rotation = [0, this.rotation[2] + 0.01, this.rotation[2] + 0.01];
  }

} 
```

package.json: 
```
{
  "name": "cchapters",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "@types/three": "^0.136.1",
    "ngx-three": "^0.12.12",
    "rxjs": "~6.6.0",
    "three": "^0.136.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.3",
    "@angular/cli": "~12.2.3",
    "@angular/compiler-cli": "~12.2.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.3.5"
  }
}
```

**Comment by niccolofanton** [comment]
The scenes renders properly but the onRender event is never triggered

**Comment by demike** [comment]
Hi, thank you for your kind words.
I looked at your example and I think everything looks right.

When looking at your package.json one thing comes into my mind:
You are using angular 12. That's actually the only real difference compared to the Loader / Controls examples.

Could you post the logs?
Or do you have the possibility to try with angular 13? 

What browsers did you use for testing?

**Comment by demike** [comment]
You may also try updating to the latest version of ngx-three.
The ObjLoaderDirective was missing in the Module.

**Comment by niccolofanton** [comment]
Hi, I've updated everything, thanks for the ObjLoaderDirective, I created a custom one to load my model but now I'm using yours. 

onRender events is still not getting triggered, I have tried on Chrome and also Safari on iOS

Log exported from chrome devTools, nothing strange here: [localhost-1642065391089.log](https://github.com/demike/ngx-three/files/7861478/localhost-1642065391089.log)

I've created a repository with my code: https://github.com/niccolofanton/ngx-three-debug

**Comment by demike** [comment]
I have found the issue:
The RxJs version is too old

ngx-three uses `EventEmiiter.observed` for testing if there are observers
The observed member was added to RxJs Observable in 7.x.x and the example uses RxJs 6.6

A quick fix is to upgrade your RxJs version to i.e. ~7.5.4

But I will release a compatibility patch version for ngx-three that makes ngx-three work with RxJs 6.x.x versions again

**Comment by niccolofanton** [comment]
Perfect! I've updated rxjs to 7.0.1 and now it's working, thanks for the quick reply!
