### ISSUE TITLE
How to repeat "loadGTLF" with interval?

### ISSUE THREAD

**Issue by edimmeduseljac** [demike/ngx-three#9]
I want to load a GLTF file every five to ten seconds, but I don't know how to do this with `ngx-three`. Of course I read the documentation about loading GLTF files, but I don`t know how to do it. 

With the following implementation in `component.html` I successfully load and display the received file:

```
<th-object3D
    loadGLTF
    [url]="url"
    [scale]="[100, 100, 100]"
    [position]="[0, 0, -3]"
>
</th-object3D>
```

However, the only problem here is that I do not know how to put the `th-object3d` into an interval.

If I try it with the `GLTFLoaderService`, I get the file, can also request it by an interval more often, but I do not know how to put the received GLTF file into the `th-object3D`. I did this with the following code, which is also included in the documentation: 

component.ts
```
...
constructor(private service: GLTFLoaderService) {
}

async ngOnInit() {
  const result: GLTF = await service.load('assets/helmet.glb');
}
```

I would really appreciate any help!

**Comment by demike** [comment]
When using the service approach you can do the following:

```
this.theObject3d.objRef = GLTF.scene;
```
where theObject3d (ThObject3d) can be injected by means of viewchild or contentchild.
Or in case you want to pack the funtionality into a directive. you can inject it into the constructor.
